language: go

services:
  - docker

go:
  - 1.13

before_install:
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - go vet -x .
  - go test -covermode=atomic -coverprofile="cover.out" .
  - goveralls -coverprofile="cover.out"

notifications:
  email: false

branches:
  only:
    - master
